name = "CuTropicalGEMM"
uuid = "c2b282c3-c9c2-431d-80f7-a1a0561ebe55"
authors = ["Xuanzhao Gao <gaoxuanzhao@gmail.com> and contributors"]
version = "0.1.1"

[deps]
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
TropicalGemmC_jll = "4f4992fb-2984-5eba-87b8-475305d0f5fc"
TropicalNumbers = "b3a74e9c-7526-4576-a4eb-79c0d4c32334"

[compat]
CUDA = "5"
TropicalGemmC_jll = "0.1.1"
TropicalNumbers = "0.6.2"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
